# Generated by Django 4.1 on 2022-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
