# Generated by Django 4.1 on 2022-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_news_published_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='last_modified',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
